### PR TITLE
[#173477806] not dropping <w:jc>'s values if they are "start" or "end"

### PR DESCRIPTION
**Pull request by jasonisgraham**

### CODE REVIEW

**Comment by jasonisgraham** [comment]
actually i should throw if theres an unexpected value for `jc` right?  cuz at the moment, the val is stripped silently and MSWord refuses to open the docx

**Comment by cwoolner** [comment]
@jasonisgraham should we adjust the various pom.xmls to use a new version?  Would we then need a change on the lsift side to use it?

**Comment by jasonisgraham** [comment]
> @jasonisgraham should we adjust the various pom.xmls to use a new version? Would we then need a change on the lsift side to use it?

pretty sure all we'd need to do is a docker build, which yknow happens on the team city build. i dont *think* im wrong about that, but we'd know fairly quickly if i am

**Comment by jasonisgraham** [comment]
@cwoolner https://github.com/LegalSifter/lsift/pull/1337 fixes the issue where shizz was still broken in the app

**Review by cwoolner — APPROVED** [review]

**Pull request merged**
